server {
    listen 80;
    server_name _;
    
    return 301 https://$host:443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/opd1-netwerken.crt;
    ssl_certificate_key /etc/nginx/certs/opd1-netwerken.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ =404;
    }
}