allow_anonymous false
password_file /mqtt/passwd

listener 1883

listener 1884
protocol websockets

listener 8883
cafile /mosquitto/config/certs/opd1-netwerken.crt
certfile /mosquitto/config/certs/opd1-netwerken.crt
keyfile /mosquitto/config/certs/opd1-netwerken.key