allow_anonymous false
password_file /mqtt/passwd

listener 1883

listener 1884
protocol websockets
<<<<<<< HEAD

listener 8883
cafile /mosquitto/config/certs/opd1-netwerken.crt
certfile /mosquitto/config/certs/opd1-netwerken.crt
keyfile /mosquitto/config/certs/opd1-netwerken.key
=======
password_file /mosquitto/config/passwd
>>>>>>> 866b1d46a05a8c41d236a9904c7dbab8f5da2fb2
